site_name: unreal_pycharm_remote_debug
theme:
  name: material
  language: en
  palette:
    - scheme: slate
      primary: blue
      accent: teal

  plugins:
  - search:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
      watch:
        - src

nav:
  - index.md
