name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:

  tests:
    uses: ./.github/workflows/reusable-unit-tests.yml

  static-analysis:
    needs: tests
    uses: ./.github/workflows/reusable-static-analysis.yml
