name: Release

on:
  workflow_dispatch:

jobs:

  static-analysis:
    uses: ./.github/workflows/reusable-static-analysis.yml

  tests:
    uses: ./.github/workflows/reusable-unit-tests.yml

  do_release:
    needs: [static-analysis, tests]
    uses: ./.github/workflows/reusable-semantic-release.yml
    permissions:
      contents: write
      id-token: write

  docs:
    needs: [tests, do_release]  # only build docs when release is successful
    uses: ./.github/workflows/reusable-build-and-deploy-docs.yml
    permissions:
      contents: write
