name: static analysis

on:
  workflow_call:
  workflow_dispatch:  # Manual trigger

jobs:

  code-analysis:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        python-version: ["3.11",]  # Unreal 5.4.4

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pip-tools
        pip-compile --output-file requirements.txt requirements.in requirements-dev.in requirements-test.in
        pip-sync requirements.txt

    - name: Analysing the code with pylint
      run: |
        pylint plugin_src/PyCharmRemoteDebug/Content/Python/  

    - name: Analysing the code with black
      uses: psf/black@stable
      with:
        src: "plugin_src/PyCharmRemoteDebug/Content/Python/"
        options: "--diff"

    - name: Analysing the code with mypy
      run: mypy plugin_src/PyCharmRemoteDebug/Content/Python/
